name: dno
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - wandb=0.16
  - ipykernel=6
  - jupyter_core=5.7
  - matplotlib=3.8
  - palettable=3.3
  - numpy=1.23
  - tqdm=4.65
  - einops=0.7
  - pytorch-cuda=12.4
  - pytorch=2.4
  - torchvision=0.19
  - torchaudio=2.4
  - transformers=4.43.2
  - torchtriton
  - typing_extensions
  - accelerate=1.0.1
  - diffusers=0.30.3
  - timm=1.0.11
  - open-clip-torch=2.24.0
  - inflect
  - pydantic
  - ipykernel=6
  - jupyter_core=5.7
  - matplotlib=3.8
  - openai=1.37
  - pip:
    - ml-collections
    - absl-py
    - ipdb
